
apiVersion: v1
kind: Pod
metadata:
 name: promo-app
spec:
 containers:
   - name: maven
     image: maven:3.5.4-jdk-8-slim
     imagePullPolicy: Always # use cache or pull image for agent
     resources:  # limits the resources your build contaienr
        requests:
          memory: "8Gi"
          cpu: "2000m"
        limits:
          memory: "2Gi


